# Generated by Django 4.2.2 on 2023-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_radius_parkingspot_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='hourly_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
