# Generated by Django 4.2.2 on 2023-07-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_requestedparking_delete_parkingrequested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedparking',
            old_name='booked_by',
            new_name='user',
        ),
    ]
